// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUPPvE_TaSU3voJWpJj9KZwVJFhu0ITvI',
    appId: '1:307341582600:web:efb1d68ee7fc4e1fedccbd',
    messagingSenderId: '307341582600',
    projectId: 'flake-16ccb',
    authDomain: 'flake-16ccb.firebaseapp.com',
    storageBucket: 'flake-16ccb.firebasestorage.app',
    measurementId: 'G-DTWJ2H13L1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8Cs0-iLlrwZncPVO3QHeZ6REe0qBNPCE',
    appId: '1:307341582600:android:9f3ac92ffba1bb4dedccbd',
    messagingSenderId: '307341582600',
    projectId: 'flake-16ccb',
    storageBucket: 'flake-16ccb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdiU5EBuLvpNm0iJoHYiQE1NwOYqFOwis',
    appId: '1:307341582600:ios:a39ef994146fd0c4edccbd',
    messagingSenderId: '307341582600',
    projectId: 'flake-16ccb',
    storageBucket: 'flake-16ccb.firebasestorage.app',
    iosBundleId: 'com.example.flake',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdiU5EBuLvpNm0iJoHYiQE1NwOYqFOwis',
    appId: '1:307341582600:ios:a39ef994146fd0c4edccbd',
    messagingSenderId: '307341582600',
    projectId: 'flake-16ccb',
    storageBucket: 'flake-16ccb.firebasestorage.app',
    iosBundleId: 'com.example.flake',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUPPvE_TaSU3voJWpJj9KZwVJFhu0ITvI',
    appId: '1:307341582600:web:59b227c1897a62f7edccbd',
    messagingSenderId: '307341582600',
    projectId: 'flake-16ccb',
    authDomain: 'flake-16ccb.firebaseapp.com',
    storageBucket: 'flake-16ccb.firebasestorage.app',
    measurementId: 'G-0DKHH4YZQ7',
  );
}
